CREATE DATABASE IF NOT EXISTS twitter_clone;

CREATE TABLE usuarios(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULl,
    senha VARCHAR(32) NOT NULL
);